<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PowerlineTool</AssemblyName>
    <RootNamespace>PowerlineTool</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Product>Powerline Tool</Product>
    <AssemblyTitle>Powerline Tool</AssemblyTitle>
    <Version>1.1.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerlineTool.Core\PowerlineTool.Core.csproj" />
  </ItemGroup>

</Project>
