<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PowerlineTool.Core</RootNamespace>
    <AssemblyName>PowerlineTool.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.0" />
  </ItemGroup>

</Project>
